### ISSUE TITLE
need resp.Body.Read() before resp.Body.Close() for reuse the tcp connection

### ISSUE THREAD

**Issue by heidawei** [rakyll/boom#60]
need resp.Body.Read() before resp.Body.Close() for reuse the tcp connection if the resp has payload, if not the tcp connection will keep alive long time,  the http.Transport have to new tcp connection

**Comment by missedone** [comment]
@rakyll 
could you take a look at the issues and PRs, for example this issue, there is three duplicate PRs around: #70, #77, and #88 
thanks

**Comment by rakyll** [comment]
This shouldnt be a problem after Go 1.4. Closing a response body must allow the Transport the reuse the underlying socket. 

If you try to discard the payload by pipeing it to ioutil.Discard after each request, it will eat your CPU.

Run the small program below and watch netstat. The socket is being reused, comment out resp.Body.Close() to see the difference. (Tested against go1.5.1 darwin/amd64)
```
func main() {
	for i := 0; i < 5000; i++ {
		resp, err := http.Get("https://google.com")
		if err == nil {
			resp.Body.Close()
		}
	}
}

```

Sorry for the late reply and reopen if I am missing out something.

**Comment by missedone** [comment]
@rakyll
the other reason i need this readAll is because, in my case, i was testing the rest api implemented with java, if boom doesn't read the data, the server side won't marshall java objects to xml which is not desiered.
from my view, close resp body directly is sort of wget header spider mode.
if you think it's waste of time to read and discard data, we might can add a flag to tell wether need thrill all data or not.
what do you think?

btw, my go version is 1.5.1
thanks

**Comment by rakyll** [comment]
Maybe we need a `-readall` flag or the inverse.
